### ISSUE TITLE
error using heat_hcl

### ISSUE THREAD

**Issue by meteosimon** [retostauffer/python-colorspace#3] opened 2021-04-22 13:38 UTC
Trying to use the cmap method of heat_hcl I get the error:

```
AttributeError: 'heat_hcl' object has no attribute '_rev'
```

I guess this attribute is not initialized?

**Comment by retostauffer** [comment] 2021-04-23 07:34
Dear Mr. Simon

Do you have a minimal to reproduce this issue? The following should work:

```
from colorspace import heat_hcl

pal1 = heat_hcl()
print(pal1(3))
print(pal1(3, rev = True))
```

I have, however, encountered another small problem where double-reverse will not work:

```
pal1 = heat_hcl(rev = True)
print(pal1(3))
print(pal1(3, rev = True))
```

... which gives twice the same series of colors (always 'reversed').

**Comment by meteosimon** [comment] 2021-04-23 07:41
The error occurs using the cmap method of the palette for matplotlib:

```
from colorspace import heat_hcl
pal = heat_hcl()
pal.cmap()
```

**Comment by retostauffer** [comment] 2021-04-23 07:51
Ok, I see the error occurs when calling

```
pal.cmap(rev = True)
```

I have to address this; Not intended to revert the `.cmap()`, the palette should be reverted instead. Does it work if you use the following:

```
from colorspace import heat_hcl
pal = heat_hcl(rev = True)
# and then use pal.cmap() from here
```

**Comment by meteosimon** [comment] 2021-04-23 08:06
I just forked the repo and added [this line](https://github.com/meteosimon/python-colorspace/blob/8922dfbe25c014a98b6ac744337f1e47f623e332/colorspace/palettes.py#L1653), it now seems to work, no error, specplot is identical to [R's colorspace](https://colorspace.r-forge.r-project.org/).

**Comment by zeileis** [comment] 2024-06-03 23:31
I think that this has been addressed. But as the current code is a bit different from what Thorsten proposed, I'm pinging Reto @retostauffer to double check...

**Comment by zeileis** [comment] 2024-06-03 23:54
Some more digging: I think this was addressed in the PR https://github.com/retostauffer/python-colorspace/pull/4

**Comment by retostauffer** [comment] 2024-06-05 06:32
That is, indeed, fixed. Reversing colors is either done when creating a colorspace palette (using the `_rev = True` argument) but can also be done later on the matplotlib cmap using e.g., `rainbow().cmap().reversed()`.

[Here is a small gist test script](https://gist.github.com/retostauffer/65dde67859bf176243ce00e2c7b2b0ee) with a quick test/example.

**Closed by retostauffer** 2024-06-05 06:32 UTC
Labels: bug
